version: '3.1'

services:
  postgres_db:
    image: postgres:15.1
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: jonidb
      POSTGRES_USER: jonathan
      POSTGRES_PASSWORD: joniSecret
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
